### ISSUE TITLE
Etwas blockiert die GPIOs

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPagerLED#8]
Mit laufendem UniPager
````
pi@raspagerc9000:~/UniPagerLED $ ./statusleds.py --hostname localhost --port 8055 --gpioConn 10 --gpioRun 11
Namespace(betrled=11, hostname='localhost', port='8055', txled=None, verbled=10)
./statusleds.py:17: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(self.bled, GPIO.OUT)
./statusleds.py:19: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(self.vled, GPIO.OUT)
Setting led 11 to 1
Resp:
{
    "Status": {
        "transmitting": false,
        "connected": true,
        "timeslots": [
            false,
            false,
            false,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            false,
            false
        ]
    }
}
Setting led 10 to 1
Led not present
^CSetting led 11 to 0
Traceback (most recent call last):
  File "./statusleds.py", line 82, in <module>
    setter.loop()
  File "./statusleds.py", line 63, in loop
    self.setstatus()
  File "./statusleds.py", line 48, in setstatus
    sres = self.ws.recv()
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 663, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 678, in recv_data
    frame = self.recv_frame()
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 753, in recv_frame
    frame_buffer.recv_header(self._recv_strict)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 257, in recv_header
    header = recv_fn(2)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 860, in _recv_strict
    bytes = self._recv(shortage)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 842, in _recv
    bytes = self.sock.recv(bufsize)
KeyboardInterrupt
pi@raspagerc9000:~/UniPagerLED $
````

Auch mit gestopptem unipager das gleiche. Was ist da los? Vor allem __Setting led 10 to 1
Led not present__

**Comment by moho1** [comment]
Ich habe dazu http://raspi.tv/2013/rpi-gpio-basics-3-how-to-exit-gpio-programs-cleanly-avoid-warnings-and-protect-your-pi gefunden. Ich schaue mir das genauer an / fixe es, wenn ich heute Abend wieder einen Pi zum ausprobieren und Zeit habe.

**Comment by dh3wr** [comment]
ok, im Übrigen trat das auch auf beim ersten Programmstart nach einem Reboot. Der unipager lief aber schon. Ich disable mal den Autostart und teste nochmal

**Comment by dh3wr** [comment]
Das gleiche mit frisch gebootetem System ohne Unipager

**Comment by dh3wr** [comment]
Vielleicht macht es auch Sinn sich https://github.com/rwth-afu/UniPagerNextion/blob/master/python_Nextion_and_LED/UniPager_Display.py anzuschauen in 2 Punkten

- Signal Handler für CTRL-C abfangen
- onMessage, on* Funktionen des websockets

Das sieht aus meiner Laien-Sicht ganz gut aus da

**Comment by moho1** [comment]
Auf meinem Pi und den GPIOs 22, 23 und 24 kommt die Warning beim ersten Start nicht. Mit GPIO 10 kann ich das auch bei Neustart nachvollziehen. Ggf. wird GPIO 10 durch Linux bereits als SPIO_MOSI initialisiert.

Ich habe in Commit d4d9092e79584f53b5553d3874947414ac9b3f23 mal die GPIO.cleanup() Funktion hinzugefügt, damit man auch sauber neustarten kann.
